### ISSUE TITLE
[Bugs] Problems found when local depoly (WIP)

### ISSUE THREAD

**Issue by yhyu13** [NExT-GPT/NExT-GPT#24]
Hi,

I started an remote instance to test local deployment

Rig :
Ubuntu 20.04
python 3.10
Cuda 11.8
RTX3090

Here is the problems I found when running the demo app locally
```
cd ./code
bash scripts/train.sh
```

1, Additional pip packages required (complained by python as missing modules, not added to requirement.txt so far)
```
omegaconf
tensorboard
```

2, Wrong local python modules

This line throws error , https://github.com/NExT-GPT/NExT-GPT/blob/88750156c700c667f6310c99c6c63022812e1209/code/header.py#L29 suggest the `data` folder in the root directory should also contain a __init__.py to become a python module? I comment this line out in order to proceed.

3, Python dict key error

Then I got this error log, it seems python is complaining about missing key. 

```
[!] load base configuration: config/base.yaml
Traceback (most recent call last):
  File "/root/CodeSapce/NextGPT/code/demo_app.py", line 28, in <module>
    args.update(load_config(args))
  File "/root/CodeSapce/NextGPT/code/config/__init__.py", line 27, in load_config
    if args['mode']:
KeyError: 'mode'
```

I changed it to 

```
if args.get('mode'):
```

And there are more dict key error on not existing keys

```
Initializing language decoder from ../ckpt/pretrained_ckpt/vicuna_ckpt/7b_v0 ...
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:07<00:00,  3.66s/it]
Traceback (most recent call last):
  File "/root/CodeSapce/NextGPT/code/demo_app.py", line 29, in <module>
    model = NextGPTModel(**args)
  File "/root/CodeSapce/NextGPT/code/model/anyToImageVideoAudio.py", line 63, in __init__
    if self.args['freeze_lm']:
KeyError: 'freeze_lm'
```

I don't think its a good practice to use [] for testing if key exists, we should use .get() instead

**Comment by ChocoWu** [comment]
Hi @yhyu13, thx for the valuable suggestions. 
We have updated our code, please consult the new version.

**Comment by yhyu13** [comment]
@ChocoWu Sorry, I tested out the latest commit , I don't think it address any of the issue mentioned early.

#1 to #5 still exists, and I am still stuck at #4 which requires additional arguments "freeze_lm" for inference time.

It seems the demo app actually allow training? Am I getting it wrong?

**Comment by ChocoWu** [comment]
@yhyu13, thx for the valuable feedback.

- For issue 1, I have made the necessary updates to the `requirements.txt` file.
- For issue 5,  you are right, and you have the flexibility to configure the CUDA_VISIBLE_DEVICES as needed.
- For issue 4, I did not meet the error, so I have no idea regarding this issue.

**Comment by hhllxx1121** [comment]
@yhyu13  I have encountered all the problems you mentioned, but I don't know how to solve the issue 4: KeyError: 'freeze_lm'

**Comment by WZFish** [comment]
issue 4 can add an arg in demo_app.py :parser.add_argument('--freeze_lm', type=bool, default=True)

**Comment by NomanTrips** [comment]
@hhllxx1121 I was able to get the demo to work for inference by doing the following (7b version):

**Code changes:**
demo_app.py
-add these lines below line 24 where args are added to the parser:
parser.add_argument('--freeze_lm', type=bool, default=True)
parser.add_argument('--freeze_input_proj', type=bool, default=True)
parser.add_argument('--freeze_output_proj', type=bool, default=True)

anyToImageVideoAudio.py
-On line 80 where the code says "r=self.args['lora_r']," change how the lora params are being fetched to fix key errors:
r=self.args.get('lora_r'),
lora_alpha=self.args.get('lora_alpha'),
lora_dropout=self.args.get('lora_dropout'),

**Libraries**
install this library for the video processing (I used the cpu variant):
pip install decord

**Issues in requirements.txt:**
PyYAML has two versions in the file? (I used 6.0.1)
torchaudio - two versions were listed, I used 0.13.1
torchvision - two version were listed, I used 0.14.1

**Tokenizer:**
I had an issue where the vicuna tokenizer wouldn't load (I followed the steps in section 3.1). I had to remove a file named "added_tokens.json" that was in /NExT-GPT/ckpt/pretrained_ckpt/vicuna_ckpt/7b_v0

**My System:**
Ubuntu 20.04.3 LTS
RTX 3090 (vram at ~ 17GB idle with weights loaded)
48 GB RAM (usage went to 45 when loading the encoders and tokenizers)
cuda 11.6

@ChocoWu Great project and paper! Bravo to the team and thanks for sharing on github :)

**Comment by yhyu13** [comment]
@NomanTrips 

Thanks, I got the demo app working.

Regards to vicuna 7b v0, I used this one over here https://huggingface.co/helloollel/vicuna-7b/tree/main with commit 521df1ed9d3a4ca04fa0209349f7ba62a05938f6 where it points to the v0 version of vicuna-7b. This is a already converted hf format weight that can be loaded w/o modification.

I also found the demo app runs on 0.0.0.0 which is risky if fire wall is not correctly configured, so to make change in the last line here https://github.com/NExT-GPT/NExT-GPT/blob/aec4026010b8caffb3d75ba518d2aaacad5d9df6/code/demo_app.py#L516 to 127.0.0.1

**Comment by eeric** [comment]
@NomanTrips 
It doesn't have that good effect as seem as https://next-gpt.github.io/
May I ask how your experiment went?
